# -*- coding: utf-8 -*-
"""Madhesh Next — canonical data: 8 districts, 136 local levels.
Source: Nepal National Population & Housing Census 2021 (CBS) / district profiles.
Types: METRO, SUB, MUN, RM
"""

PROVINCE = {
    "name_en": "Madhesh Province",
    "name_ne": "मधेश प्रदेश",
    "capital_en": "Janakpurdham",
    "capital_ne": "जनकपुरधाम",
    "population": 6114600,
    "area_km2": 9661,
    "districts": 8,
    "local_levels": 136,
    "density": 633,
    "share_of_country_area": "6.5%",
}

DISTRICTS = [
    {
        "slug": "saptari", "en": "Saptari", "ne": "सप्तरी",
        "hq_en": "Rajbiraj", "hq_ne": "राजविराज",
        "pop": 706255, "area": 1363, "lit": "67.7%",
        "note_en": "Eastern gateway of Madhesh, on the Koshi. Rice, fisheries and the Koshi Tappu wetland economy; strong out-migration of youth.",
        "note_ne": "मधेशको पूर्वी प्रवेशद्वार, कोशीको किनारमा। धान, मत्स्यपालन र कोशी टप्पुको सिमसार अर्थतन्त्र; युवाको उच्च बहिर्गमन।",
        "lgs": [
            ("Rajbiraj", "राजविराज", "MUN"),
            ("Kanchanrup", "कञ्चनरुप", "MUN"),
            ("Dakneshwori", "दक्नेश्वरी", "MUN"),
            ("Bodebarsain", "बोदेबरसाइन", "MUN"),
            ("Khadak", "खडक", "MUN"),
            ("Shambhunath", "शम्भुनाथ", "MUN"),
            ("Surunga", "सुरुङ्गा", "MUN"),
            ("Hanumannagar Kankalini", "हनुमाननगर कङ्कालिनी", "MUN"),
            ("Saptakoshi", "सप्तकोशी", "MUN"),
            ("Tilathi Koiladi", "तिलाठी कोइलाडी", "RM"),
            ("Rupani", "रुपनी", "RM"),
            ("Balan-Bihul", "बलान-बिहुल", "RM"),
            ("Bishnupur", "विष्णुपुर", "RM"),
            ("Chhinnamasta", "छिन्नमस्ता", "RM"),
            ("Mahadeva", "महादेवा", "RM"),
            ("Tirahut", "तिरहुत", "RM"),
            ("Rajgadh", "राजगढ", "RM"),
            ("Agnisair Krishna Savaran", "अग्निसाइर कृष्णासवरन", "RM"),
        ],
    },
    {
        "slug": "siraha", "en": "Siraha", "ne": "सिराहा",
        "hq_en": "Siraha", "hq_ne": "सिराहा",
        "pop": 739953, "area": 1188, "lit": "65.1%",
        "note_en": "Lahan and Mirchaiya anchor a busy East–West Highway trade belt; sugarcane, lentils and a growing service economy.",
        "note_ne": "लहान र मिर्चैया पूर्व–पश्चिम राजमार्गको व्यापारिक पेटीका केन्द्र; उखु, दलहन र बढ्दो सेवा अर्थतन्त्र।",
        "lgs": [
            ("Siraha", "सिराहा", "MUN"),
            ("Lahan", "लहान", "MUN"),
            ("Dhangadhimai", "धनगढीमाई", "MUN"),
            ("Golbazar", "गोलबजार", "MUN"),
            ("Mirchaiya", "मिर्चैया", "MUN"),
            ("Kalyanpur", "कल्याणपुर", "MUN"),
            ("Karjanha", "कर्जन्हा", "MUN"),
            ("Sukhipur", "सुखीपुर", "MUN"),
            ("Arnama", "अर्नमा", "RM"),
            ("Aurahi", "औरही", "RM"),
            ("Bariyarpatti", "बरियारपट्टी", "RM"),
            ("Bhagwanpur", "भगवानपुर", "RM"),
            ("Bishnupur", "विष्णुपुर", "RM"),
            ("Lakshmipur Patari", "लक्ष्मीपुर पतारी", "RM"),
            ("Naraha", "नरहा", "RM"),
            ("Navarajpur", "नवराजपुर", "RM"),
            ("Sakhuwanankarkatti", "सखुवानान्कारकट्टी", "RM"),
        ],
    },
    {
        "slug": "dhanusha", "en": "Dhanusha", "ne": "धनुषा",
        "hq_en": "Janakpurdham", "hq_ne": "जनकपुरधाम",
        "pop": 867747, "area": 1181, "lit": "65.2%",
        "note_en": "Provincial capital and Mithila's cultural centre. Rail link to India, religious tourism, and the province's largest urban consumer market.",
        "note_ne": "प्रदेशको राजधानी र मिथिलाको सांस्कृतिक केन्द्र। भारतसँग रेल जोडाइ, धार्मिक पर्यटन र प्रदेशकै ठूलो सहरी उपभोक्ता बजार।",
        "lgs": [
            ("Janakpurdham", "जनकपुरधाम", "SUB"),
            ("Chhireshwarnath", "क्षिरेश्वरनाथ", "MUN"),
            ("Ganeshman Charnath", "गणेशमान चारनाथ", "MUN"),
            ("Dhanusadham", "धनुषाधाम", "MUN"),
            ("Nagarain", "नगराइन", "MUN"),
            ("Bideha", "विदेह", "MUN"),
            ("Mithila", "मिथिला", "MUN"),
            ("Shahidnagar", "शहीदनगर", "MUN"),
            ("Sabaila", "सबैला", "MUN"),
            ("Kamala", "कमला", "MUN"),
            ("Mithila Bihari", "मिथिला बिहारी", "MUN"),
            ("Hansapur", "हंसपुर", "MUN"),
            ("Janaknandini", "जनकनन्दिनी", "RM"),
            ("Bateshwar", "बटेश्वर", "RM"),
            ("Mukhiyapatti Musharniya", "मुखियापट्टी मुसहरमिया", "RM"),
            ("Lakshminiya", "लक्ष्मीनिया", "RM"),
            ("Aurahi", "औरही", "RM"),
            ("Dhanauji", "धनौजी", "RM"),
        ],
    },
    {
        "slug": "mahottari", "en": "Mahottari", "ne": "महोत्तरी",
        "hq_en": "Jaleshwar", "hq_ne": "जलेश्वर",
        "pop": 705838, "area": 1002, "lit": "59.8%",
        "note_en": "Bardibas sits at the junction of the East–West Highway and the BP Highway to Kathmandu — the province's most under-used logistics position.",
        "note_ne": "बर्दिबास पूर्व–पश्चिम राजमार्ग र बीपी राजमार्गको दोबाटोमा — प्रदेशकै सबैभन्दा कम उपयोग भएको लजिस्टिक स्थान।",
        "lgs": [
            ("Jaleshwar", "जलेश्वर", "MUN"),
            ("Bardibas", "बर्दिबास", "MUN"),
            ("Gaushala", "गौशाला", "MUN"),
            ("Loharpatti", "लोहरपट्टी", "MUN"),
            ("Ramgopalpur", "रामगोपालपुर", "MUN"),
            ("Manara Shiswa", "मनरा शिसवा", "MUN"),
            ("Matihani", "मटिहानी", "MUN"),
            ("Bhangaha", "भँगाहा", "MUN"),
            ("Balwa", "बलवा", "MUN"),
            ("Aurahi", "औरही", "MUN"),
            ("Ekdanra", "एकडारा", "RM"),
            ("Mahottari", "महोत्तरी", "RM"),
            ("Pipara", "पिपरा", "RM"),
            ("Samsi", "साम्सी", "RM"),
            ("Sonama", "सोनमा", "RM"),
        ],
    },
    {
        "slug": "sarlahi", "en": "Sarlahi", "ne": "सर्लाही",
        "hq_en": "Malangwa", "hq_ne": "मलंगवा",
        "pop": 862470, "area": 1259, "lit": "60.3%",
        "note_en": "Sugarcane and agro-processing heartland; Lalbandi and Hariwan form an emerging highway industrial corridor.",
        "note_ne": "उखु र कृषि–प्रशोधनको केन्द्रभूमि; लालबन्दी र हरिवन उदीयमान राजमार्ग औद्योगिक कोरिडोर।",
        "lgs": [
            ("Malangwa", "मलंगवा", "MUN"),
            ("Lalbandi", "लालबन्दी", "MUN"),
            ("Hariwan", "हरिवन", "MUN"),
            ("Haripur", "हरिपुर", "MUN"),
            ("Haripurwa", "हरिपुर्वा", "MUN"),
            ("Ishworpur", "ईश्वरपुर", "MUN"),
            ("Barahathwa", "बरहथवा", "MUN"),
            ("Balara", "बलरा", "MUN"),
            ("Godaita", "गोडैटा", "MUN"),
            ("Bagmati", "बागमती", "MUN"),
            ("Kabilasi", "कविलासी", "MUN"),
            ("Basbariya", "बसबरिया", "RM"),
            ("Bishnu", "विष्णु", "RM"),
            ("Brahampuri", "ब्रह्मपुरी", "RM"),
            ("Chakraghatta", "चक्रघट्टा", "RM"),
            ("Chandranagar", "चन्द्रनगर", "RM"),
            ("Dhankaul", "धनकौल", "RM"),
            ("Kaudena", "कौडेना", "RM"),
            ("Parsa", "पर्सा", "RM"),
            ("Ramnagar", "रामनगर", "RM"),
        ],
    },
    {
        "slug": "rautahat", "en": "Rautahat", "ne": "रौतहट",
        "hq_en": "Gaur", "hq_ne": "गौर",
        "pop": 813573, "area": 1126, "lit": "57.8%",
        "note_en": "The most municipalised district in Nepal — 16 municipalities — and the province's lowest literacy rate. Chandrapur links it to the highway economy.",
        "note_ne": "नेपालमै सबैभन्दा बढी नगरपालिका भएको जिल्ला — १६ नगरपालिका — र प्रदेशकै न्यून साक्षरता। चन्द्रपुरले राजमार्ग अर्थतन्त्रसँग जोड्छ।",
        "lgs": [
            ("Gaur", "गौर", "MUN"),
            ("Chandrapur", "चन्द्रपुर", "MUN"),
            ("Garuda", "गरुडा", "MUN"),
            ("Baudhimai", "बौधीमाई", "MUN"),
            ("Brindaban", "बृन्दावन", "MUN"),
            ("Dewahi Gonahi", "देवाही गोनाही", "MUN"),
            ("Gadhimai", "गढीमाई", "MUN"),
            ("Gujara", "गुजरा", "MUN"),
            ("Ishanath", "ईशनाथ", "MUN"),
            ("Katahariya", "कटहरिया", "MUN"),
            ("Madhav Narayan", "माधव नारायण", "MUN"),
            ("Maulapur", "मौलापुर", "MUN"),
            ("Paroha", "परोहा", "MUN"),
            ("Phatuwa Bijayapur", "फतुवा बिजयपुर", "MUN"),
            ("Rajdevi", "राजदेवी", "MUN"),
            ("Rajpur", "राजपुर", "MUN"),
            ("Durga Bhagwati", "दुर्गा भगवती", "RM"),
            ("Yamunamai", "यमुनामाई", "RM"),
        ],
    },
    {
        "slug": "bara", "en": "Bara", "ne": "बारा",
        "hq_en": "Kalaiya", "hq_ne": "कलैया",
        "pop": 743975, "area": 1190, "lit": "64.5%",
        "note_en": "Nepal's industrial spine. Simara–Nijgadh hosts the country's densest manufacturing cluster and the planned international airport.",
        "note_ne": "नेपालको औद्योगिक मेरुदण्ड। सिमरा–निजगढमा देशकै घना उत्पादन क्लस्टर र प्रस्तावित अन्तर्राष्ट्रिय विमानस्थल।",
        "lgs": [
            ("Kalaiya", "कलैया", "SUB"),
            ("Jitpur Simara", "जीतपुर सिमरा", "SUB"),
            ("Kolhabi", "कोल्हवी", "MUN"),
            ("Nijgadh", "निजगढ", "MUN"),
            ("Mahagadhimai", "महागढीमाई", "MUN"),
            ("Simraungadh", "सिम्रौनगढ", "MUN"),
            ("Pacharauta", "पचरौता", "MUN"),
            ("Pheta", "फेटा", "RM"),
            ("Bishrampur", "विश्रामपुर", "RM"),
            ("Prasauni", "प्रसौनी", "RM"),
            ("Adarsh Kotwal", "आदर्श कोतवाल", "RM"),
            ("Karaiyamai", "करैयामाई", "RM"),
            ("Devtal", "देवताल", "RM"),
            ("Parwanipur", "परवानीपुर", "RM"),
            ("Baragadhi", "बारागढी", "RM"),
            ("Suwarna", "सुवर्ण", "RM"),
        ],
    },
    {
        "slug": "parsa", "en": "Parsa", "ne": "पर्सा",
        "hq_en": "Birgunj", "hq_ne": "वीरगन्ज",
        "pop": 654471, "area": 1353, "lit": "69.1%",
        "note_en": "Birgunj is Nepal's commercial gateway — the largest customs point in the country and the province's only metropolitan city.",
        "note_ne": "वीरगन्ज नेपालको व्यापारिक प्रवेशद्वार — देशकै ठूलो भन्सार नाका र प्रदेशको एक मात्र महानगरपालिका।",
        "lgs": [
            ("Birgunj", "वीरगन्ज", "METRO"),
            ("Bahudarmai", "बहुदरमाई", "MUN"),
            ("Parsagadhi", "पर्सागढी", "MUN"),
            ("Pokhariya", "पोखरिया", "MUN"),
            ("Bindabasini", "विन्दबासिनी", "RM"),
            ("Dhobini", "धोबिनी", "RM"),
            ("Chhipaharmai", "छिपहरमाई", "RM"),
            ("Jagarnathpur", "जगरनाथपुर", "RM"),
            ("Jirabhawani", "जिरा भवानी", "RM"),
            ("Kalikamai", "कालिकामाई", "RM"),
            ("Pakaha Mainpur", "पकाहा मैनपुर", "RM"),
            ("Paterwa Sugauli", "पटेर्वा सुगौली", "RM"),
            ("Sakhuwa Prasauni", "सखुवा प्रसौनी", "RM"),
            ("Thori", "ठोरी", "RM"),
        ],
    },
]

TYPE_LABEL = {
    "METRO": ("Metropolitan City", "महानगरपालिका", "pill--metro"),
    "SUB":   ("Sub-Metropolitan City", "उपमहानगरपालिका", "pill--sub"),
    "MUN":   ("Municipality", "नगरपालिका", "pill--mun"),
    "RM":    ("Rural Municipality", "गाउँपालिका", "pill--rm"),
}

CONVENERS = [
    {"name_en": "Prashant Singh", "name_ne": "प्रशान्त सिंह",
     "bio_en": "Author of the Madhesh Next founding note. Works on public discourse, institutions and regional economic strategy.",
     "bio_ne": "मधेश नेक्स्टको स्थापना–दस्तावेजका लेखक। सार्वजनिक विमर्श, संस्था र क्षेत्रीय आर्थिक रणनीतिमा कार्यरत।"},
    {"name_en": "Anil Mahaseth", "name_ne": "अनिल महासेठ",
     "bio_en": "Convener focused on enterprise, trade and the role of local government as an economic actor.",
     "bio_ne": "उद्यम, व्यापार र स्थानीय सरकारको आर्थिक भूमिकामा केन्द्रित संयोजक।"},
    {"name_en": "Sanjog Dev", "name_ne": "सञ्जोग देव",
     "bio_en": "Convener working on technology, data and the digital infrastructure of the campaign.",
     "bio_ne": "प्रविधि, तथ्याङ्क र अभियानको डिजिटल पूर्वाधारमा कार्यरत संयोजक।"},
    {"name_en": "Ajay Pandey", "name_ne": "अजय पाण्डे",
     "bio_en": "Convener engaged with education, skills and the bridge between colleges and the local economy.",
     "bio_ne": "शिक्षा, सीप र क्याम्पस–स्थानीय अर्थतन्त्र सम्बन्धमा संलग्न संयोजक।"},
    {"name_en": "Bala Krishna", "name_ne": "बालकृष्ण",
     "bio_en": "Convener working on civic organisation, district chapters and community outreach.",
     "bio_ne": "नागरिक संगठन, जिल्ला च्याप्टर र सामुदायिक पहुँचमा कार्यरत संयोजक।"},
]
